### ISSUE TITLE
0.5 and 0.5.1 Won't Launch

### ISSUE THREAD

**Issue by Ephjizilla** [becast/YouPloader#17]
I've tried both the exe and zip downloads. The exe seems to install fine but trying to run the program results in nothing happening.  Same with the jar.  If I try to launch it via the prompt I also get a "cannot find main class" message.

0.4 launches without any problems.

**Comment by becast** [comment]
That is very weird. Can you uninstall the previous Version, rename your %Userdata%/YouPloader dir  and install 0.5 and try again?

**Comment by becast** [comment]
Before doing this could you attach your applog.html? It's in your %Userdata%/YouPloader dir

**Comment by Ephjizilla** [comment]
I can't seem to locate that directory.  I do have a logfile.html in my Youploader user directory.

**Comment by becast** [comment]
That is the one.

**Comment by Ephjizilla** [comment]
Here you go. 
[logfile.zip](https://github.com/becast/YouPloader/files/256869/logfile.zip)

**Comment by becast** [comment]
Apparently some weirdness going on with loading your uploads and the DB connection closing in the meantime. Will investigate in detail later today.
