### ISSUE TITLE
Doesn't resume after unexpected disconnection

### ISSUE THREAD

**Issue by Ephjizilla** [becast/YouPloader#2]
If your net goes down while a video is uploading, it seems to believe the upload is complete. When you go to YT after reconnecting, the video will be processing. It'd be good if it recognised when your net went down and treated it like you'd pressed Stop, so you could resume later.

**Comment by becast** [comment]
Thanks for letting me know! Definitely an issue that needs to be fixed.

**Comment by becast** [comment]
Little update: I delved deep into this issue this evening. It seems if your connection only fails intermittently it resumes without a hitch and without intervention. However if your connection fails completely or for a period of time it will close the connection and fail (which the program incorrectly labels as complete at this time). I will look into "resetting" the failed upload to a resume-able state, however it is possible that YouTube itself will count it as "complete" and as such the Upload may have to be labled as failed and restarted.
