### ISSUE TITLE
[Feature Request] Better handling of attempting to add videos with no title

### ISSUE THREAD

**Issue by ClefAria** [becast/YouPloader#22]
The program should just stop you from trying to upload a video without a title (or throw in a default one)--if I remember correctly, on YouTube's website, it won't let you have a video with no title.

As of now, you can add a title-less video to the queue, but when you try to begin uploading, nothing happens. Discovered this while trying to upload random files to test the upload speed, and figured out the cause through trial and error.

Just a little quality of life thing that should go into the next version, imo.

**Comment by becast** [comment]
Huh, strange I thought I had a case handling that. Will look into it and fix it! Thanks for reporting!

**Comment by becast** [comment]
Derp. I had a case that handled not selecting a file. Thanks!
