### ISSUE TITLE
Lost queues and unable to edit videos in queue

### ISSUE THREAD

**Issue by MrGazillion** [becast/YouPloader#24]
YouPloader 0.6
  
Described in detail on the Reddit thread here: https://www.reddit.com/r/letsplay/comments/4irdrw/youploader_alpha_06_released/d3auymc
  

[YouPloader.zip](https://github.com/becast/YouPloader/files/271552/YouPloader.zip)

**Comment by becast** [comment]
The zip is sadly empty. Do you use the field game title? Because Issue #23 was recently fixed and sounds an awful lot like yours.

**Comment by MrGazillion** [comment]
I do and that sounds a lot like what I was experiencing. The first time I
used it the first upload worked but I had forgotten to set the game title

**Comment by becast** [comment]
In the linked issue there is a developer Version that should fix the issue please download it and try again.

**Comment by becast** [comment]
Duplicate of #23
