### ISSUE TITLE
Upload not working after one upload?

### ISSUE THREAD

**Issue by MidnightBlaze714** [becast/YouPloader#26]
**YouPloader Version:** 
0.7
  
**Issue description:**  
 I was able to upload one video, but when I tried to upload a second video, hitting start doesn't make anything happen.

*Please attach your %userprofile%\YouPloader\logfile.html and, if necessary, any Screenshots showing the issue to this post*
https://drive.google.com/file/d/0B_ey30itogEtc0dpbWdVQXNSSXc/view?usp=sharing

**Comment by becast** [comment]
Create a backup of your %userprofile%\YouPloader folder and delete it. Launch YouPloader and see if the error persists.

**Comment by MidnightBlaze714** [comment]
Sorry I forgot to reply to this. Restarting my computer was all I needed. It just got a little buggy on me, haha.
