### ISSUE TITLE
Gametitle doesn't take place on Youtube

### ISSUE THREAD

**Issue by Avalarion90** [becast/YouPloader#27]
**YouPloader Version:**  0.7
  
**Issue description:**  I uploaded some Videos and added a gametitle in YouPloader. After the Videos were uploaded to youtube there wasn't a gametitle so i had to add it manually on youtube. The Log says Upload failed but the Videos were uploaded to youtube.
  
*Please attach your %userprofile%\YouPloader\logfile.html and, if necessary, any Screenshots showing the issue to this post*
http://filehorst.de/download.php?file=bzAwChuc

**Comment by becast** [comment]
Strange, according to your log the game title For Legend of Zelda: Windwalker was successfully set. The other Videos don't seem to have had a game title set.

**Comment by Avalarion90** [comment]
I tried it now with World of Warcraft and Fallout 4 but i had to set the gametitle manually on youtube.
http://filehorst.de/d/biGxkyHa

I use Windows 10 and Java Version 8 Update 91 maybe this helps.

**Comment by becast** [comment]
Seltsam, das logfile sagt der Titel wurde erfolgreich gesetzt. Hab es jetzt bei mir ausprobiert mit Fallout 4 und es funktioniert. Nehm stark an dass es an YT liegt denn:

```
20:17:21.719 	Uploader-39 	INFO 	at.becast.youploader.youtube.upload.MetadataUpdater 	Updating Metadata for Video DJvcmIUItO4 	
20:17:21.727 	Uploader-39 	DEBUG 	at.becast.youploader.youtube.upload.MetadataUpdater 	Data allow_comment_ratings=yes&modified_fields=allow_comment_ratings,video_monetization_style,syndication,allow_comments_detail,product_placement,creator_share_feeds,allow_comments,self_racy,game_title,ad_formats&syndication=everywhere&creator_share_feeds=yes&allow_comments=yes&self_racy=no&game_title={"mid":"/m/06zmzsz"}&session_token=html lang=&video_monetization_style=ads&allow_comments_detail=all&product_placement={"has_paid_product_placement":false}&ad_formats={"has_overlay_ads":true,"has_skippable_video_ads":true,"has_non_skippable_video_ads":false,"has_long_non_skippable_video_ads":false,"has_product_listing_ads":false}&video_id=DJvcmIUItO4 	
20:17:21.879 	Uploader-39 	DEBUG 	at.becast.youploader.youtube.upload.MetadataUpdater 	Response code 200
```
Hier wird der Titel erfolgreich gesetzt (sieht bei mir genau gleich aus und es funktioniert).

**Comment by becast** [comment]
Halt stop! Grade sehe ich dass dein Session token fehlt! Werde mir das ansehen!

**Comment by Avalarion90** [comment]
Das Problem besteht mit der neusten Version immer noch bei mir. https://gist.github.com/anonymous/e3656f00f01ccaa0983ff785c84e4b87

**Comment by becast** [comment]
Das log sagt das YouPloader den YT session Token nicht auf der YT Seite findet. Das ist meistens wenn das Cookie nicht mehr gültig ist. YouTube hat es nicht möglich gemacht Monetarisierung und Spieletitel in der API zu übergeben also macht YouPloader dass mit dem Trick es als "Browser" zu machen. 
 
Wenn du einen Account hinzufügst stelle sicher dass du "Angemeldet bleiben" ankreuzt und dass dein YT Kanal der Standardkanal deines Google Accounts ist. Das ganze ist kein Bug vielmehr ist es einfach Youtube das nicht kooperiert und die arbeiten an der API in dieser hinsicht eingestellt hat: https://code.google.com/p/gdata-issues/issues/detail?id=4770&can=1&q=label%3AAPi-YouTube&colspec=API%20ID%20Type%20Status%20Priority%20Stars%20Summary&start=100

In diesem Sinne ist der ganze Metadaten Updater von YouPloader eher "toll wenns funktioniert".

Sorry dass ich keine bessere antwort geben kann.

**Comment by Avalarion90** [comment]
Sehr schade, dass das nicht Funktioniert. Ist aber eine Schande, dass Youtube diese Sachen nicht mittels der API unterstützt. Hoffentlich fügen sie das in nächster Zeit mal hinzu ^^
