### ISSUE TITLE
Issue Linking to YouTube Account

### ISSUE THREAD

**Issue by MidnightBlaze714** [becast/YouPloader#28]
**YouPloader Version:**  
0.7
  
**Issue description:**  
When I go through all the steps to connect to my YouTube account, the internet browser window disappears like everything connected properly, but the window with the code to connect remains. I've tried restarting my laptop and restarting my YouPloader session with no success.
  
*Please attach your %userprofile%\YouPloader\logfile.html and, if necessary, any Screenshots showing the issue to this post*

http://s000.tinyupload.com/index.php?file_id=10135922468269251452

**Comment by Tom6789** [comment]
Do you have an Internet connection? There are many UnknownHostException s. Maybe Theres somthing with your dns? Or does the Firewall block YoupLoader?

-----
Idont even know this program, and you may delete this reply at any Time. This is just what I found out. @MidnightBlaze714

**Comment by becast** [comment]
This is an Issue since you use IPv6 which is not supported everywhere. Will be fixed in 0.9
