### ISSUE TITLE
Can't requeue a video that you previously queued but cancelled uploading unless you restart

### ISSUE THREAD

**Issue by Ephjizilla** [becast/YouPloader#3]
I added a video to the Queue and started uploading, then realised that I hadn't set it to Scheduled. So I Cancelled Upload and went back to the Video Settings tab. I changed it to Scheduled and chose the video file again, but when I clicked Add to Queue, it wouldn't put it in the queue. When I restarted the program, it did add it to the queue.

**Comment by becast** [comment]
Cancelling is only if you really want an upload to really not upload again, you can edit Uploading videos by clicking the pen icon on the upload and the information will be corrected.

**Comment by Ephjizilla** [comment]
Cool, so if I click edit and change a video from Public to Scheduled, it will release it at the scheduled date instead?

**Comment by becast** [comment]
Yes. You can change everything except the file :)

**Comment by Ephjizilla** [comment]
Excellent!

**Comment by becast** [comment]
Changed the behaviour. Cancelling now DELETES the upload in progress on YouTube and states that it is aborted. However with the edit button you can recall and re-add the upload.
