### ISSUE TITLE
YouPloader doesn't launch

### ISSUE THREAD

**Issue by koosemose** [becast/YouPloader#40]
**YouPloader Version:**  
  0.9

**Issue description:**  
 YouPloader never launches, from exe or jar. I've never ran YouPloader before, but after it initially failed I tried installing older versions (which launched), and upgrading a step at a time, deleted %userprofile%\YouPloader\data every step along the way.

[logfile.zip](https://github.com/becast/YouPloader/files/568262/logfile.zip)

**Comment by becast** [comment]
Please update you Java to the latest Version (111 or 112) as your version is dangerously outdated (60)
