### ISSUE TITLE
Stuck at Updating Metadata

### ISSUE THREAD

**Issue by Avalarion90** [becast/YouPloader#41]
**YouPloader Version:**  0.9
  
**Issue description:**  The Upload works just fine but the program stucks at Updating Metadata and doesn't start the next Upload. I have to restart YouPloader to start the next Upload.
[logfile_.zip](https://github.com/becast/YouPloader/files/570701/logfile_.zip)

**Comment by Filgaja** [comment]
Same Problem:

i made a list of uploads, went to bed. and when i stood up the first video where uploaded nearly finished... but it wasnt. It stucked at Meta Data and after i restarted, it was "finished" but the video isnt online at my chanel.

[logfile.zip](https://github.com/becast/YouPloader/files/573731/logfile.zip)

**Comment by Filgaja** [comment]
I think i know when it happened... i started uploading and had to edit some things like date and stuff... and then i saved it. maybe to change stuff during upload bring this problem?

**Comment by Avalarion90** [comment]
I just realised that the second upload starts after i clicked on stop and then on start again.
And i didn't edit my Uploads after i added them to the Queue
[logfile.zip](https://github.com/becast/YouPloader/files/586198/logfile.zip)

**Comment by becast** [comment]
Did 0.9.1 do anything to your issue?

**Comment by becast** [comment]
Closed until further comments.
