### ISSUE TITLE
Raw File Name changes

### ISSUE THREAD

**Issue by Filgaja** [becast/YouPloader#42]
YouPloader 0.9
  
If i upload a File with Youploader the Name of the Raw File changes on Youtube.

For Example after i click on edit button >

With YouPloader:
RAW-Datei: this+is+my+filename+with+spaces.mp4

With Upload Button on Youtube: 
RAW-Datei: this is my filename with spaces - Kopie.mp4 
  
I think this is importand because of SEO issues.
I am using Tags and Video relevant words for a better search rank as raw file name... But i do not know how much the "+" effects the ranking instead of real spaces.

All i could find on Google was this code i believe it is c++ or PHP but not java:
rawurldecode() verwandelt beim Dekodieren Pluszeichen ('+') nicht in Leerzeichen. Dies erledigt urldecode().

I dont know if there is a possibility to fix this problem.

Any ideas?

**Comment by becast** [comment]
The raw filename is not used for SEO as confirmed by Youtube. https://www.reddit.com/r/youtube/comments/3x55ww/is_there_any_evidence_that_the_raw_video_file/cy1ppya/
