### ISSUE TITLE
Token Expired and Upload stoped at nearly 99%

### ISSUE THREAD

**Issue by Filgaja** [becast/YouPloader#44]
YouPloader 0.9.1

I put several videos in a queue last night. When i stood up this morning only 2 where uploaded and the third video was on 98,**%.
The Video was available on YouTube with all information's (description, tags, etc) but without the thumbnail.

I used the auto installer yesterday to update and after installation I also logged in again new. It seems there where no issues with installation.

I also tried to restart Youploader when i saw this problem accured but after restart nothign happend.
I changed the Thumbnail manuel on youtube and deleted this video in YouPloader queue :)

It is the video from this line:
```
<tr class="info even">
<td class="Date">02:19:52.797</td>
```

And it seems it happened because the token expired:
`<td class="Date">09:00:03.682</td>`

[logfile.zip](https://github.com/becast/YouPloader/files/615754/logfile.zip)

**Comment by becast** [comment]
Thanks for the notification, I see nothing obviously wrong in the log, the expired Token notice is not concerning. I'll keep an eye on it but since it seemingly went through I assume Youtube or your Internet had a hiccup. I'll keep this open, please let me know if it happens again.

**Comment by becast** [comment]
Did it happen again?

**Comment by MrKlobluerste** [comment]
YouPloader 0.9.3

Hi, same issue here after updating to 0.9.3. I put lot of videos in a queue, after 3-4 videos the program has stop the upload. The logfile can you find here: [Here](https://gist.github.com/anonymous/7cbcb42d9638370a209575d4ce6019c5)

**Comment by becast** [comment]
Thanks, in the logfiles are errors, so I'll have a look at it!
I might need you to download a different jar file to see what exactly YouTube replies as error.

**Comment by Juliusvanvern** [comment]
Which jar file?

**Comment by becast** [comment]
I'll leave a link here once it is done.

**Comment by Juliusvanvern** [comment]
Ok, maybe I misunderstood you. 👍

**Comment by Juliusvanvern** [comment]
Hey.. any new update? :) The problem is still exist :-(

**Comment by becast** [comment]
This bug should vanish with 0.9.4

**Comment by Juliusvanvern** [comment]
Thank you 👍 :)
