### ISSUE TITLE
Episode # and %ep%

### ISSUE THREAD

**Issue by Donzii** [becast/YouPloader#45]
**YouPloader Version:** 
0.9.2 (updated install, no fresh)
  
**Issue description:**  
Episode # can be used in the Title and Thumbnail with %ep%
`Uploader-52	INFO	at.becast.youploader.youtube.upload.UploadManager	Uploading Thumbnail H:\Bilder\fertige Bilder\twdanf_%ep%.png`
`java.io.FileNotFoundException: H:\Bilder\fertige Bilder\twdanf_%ep%.png (Das System kann die angegebene Datei nicht finden) `

Or did i anything wrong?
![yp092](https://cloud.githubusercontent.com/assets/7527643/22066724/940dbfd6-dd8e-11e6-970a-6a041bcd50cf.png)

Got tested with #%ep% or %ep% and Episode #01, same

Logfile: search "Log session start time Wed Jan 18 13:16:16 CET 2017"
[logfile.zip](https://github.com/becast/YouPloader/files/714038/logfile.zip)

Test it later with a fresh DB and new Java 121, released today

**Comment by Filgaja** [comment]
Done the same

episode window: 297

titel: test %ep% test

thumbnail: E:\Thumbnails\Monster Hunter Online\%ep%.jpg

The titel on youtube is still "test %ep% test" withouth changing it to the episode... should be "test 297 test" after upload

**Comment by becast** [comment]
Seems to be a bug, will check it out

**Comment by becast** [comment]
Schould be fixed in the Hotfix release
