### ISSUE TITLE
Java error on launch

### ISSUE THREAD

**Issue by RealityExit** [becast/YouPloader#46]
**YouPloader Version:**  v0.9.2-beta
  
**Issue description:**  Immediate java error on launch, application never opens.

Worked fine on previous version, nothing else changed.
I looked at the log file, it doesn't generate anything at all, but I can still upload it if you like.

http://i.imgur.com/BnOQ7BV.png

Windows 10 x64
Java 8 Update 121

**Comment by becast** [comment]
Just tried with Java 121, and it worked fine. Maybe reinstall java. Seems not be directly related to YouPloader.

**Comment by RealityExit** [comment]
I updated it from some previous version that I was also having problems with to 121, I'll try a complete reinstall later.

**Comment by becast** [comment]
Alternatively launch it from the console with java -jar path/to/you/youploader.jar this should give you an error message

**Comment by RealityExit** [comment]
Did Java reinstall, launched it with cmd and returned this.

http://i.imgur.com/70xyzk7.png

**Comment by becast** [comment]
I added a commit that should hopefully circumvent this issue + updated to the latest jna

**Comment by becast** [comment]
Should be fixed in the Hotfix release. please let me know.

**Comment by RealityExit** [comment]
Fixed indeed.  Great work, thank you.

**Comment by becast** [comment]
Great thanks for your feedback!
