### ISSUE TITLE
YouPloader only uploads 2 Videos...

### ISSUE THREAD

**Issue by Filgaja** [becast/YouPloader#47]
...  and then stop to go further uploading the next in line

Version: 0.93
  
I put 10 Videos inside Uploader this night, but it only uploaded 2 Videos (003 and 004) untill finish...
this morning as i stood up i had to restart YouPloader to go on with Video 005

YoupLoader only uploaded 2 Videos again (005 and 006) and stoped working again.

The Video Files are around 5 GB filesize and one Video need arround 1 Hour and a few Minutes to upload.

Here is a clean logfile (I cleaned it up before i started to upload the 10 Files to be sure there are no older entrys in it for you to check)
  
https://gist.github.com/anonymous/3153f3b4d899c497edc236b5a93fab32

[logfile.zip](https://github.com/becast/YouPloader/files/801947/logfile.zip)

**Comment by Filgaja** [comment]
Yes it only uploads 2 Videos and stops then. Happened once again:

Here is the logfile before i closed it to restart to upload next videos:

https://gist.github.com/anonymous/ce605f2478377d4521d07ea42576bad8

**Comment by NoxoN1602** [comment]
exactly the same issue here..

**Comment by becast** [comment]
Hello. Thanks for reporting the issue, I experienced this myself on occasion, and it has to do with YouTube sending an invalid reply to the next upload, sadly I'm not sure yet why Youtube does that aside from being... well YouTube. I'm adding some more debug information to hopefully find out what the reply is exactly and hopefully it will clear up what and why this is happening.

**Comment by Filgaja** [comment]
Okay good to know... i switched back to version 0.9.1 > there is no problems with thumbnails at the moment. Every Thumbnail is fully uplaoded.

The Thumbnails are all under 2 mb and are policies of Youtube File format.
If i would guess >

On Some Episodes it takes me around One and a half our because of the file size and it seems at the end of the upload it does not recognize the thumbnail upload information from 1 and a half houre before.

I dont know if this happen after a token refresh but it happen randomly since the new %ep% system (0.9.3) i tyed with "%ep%.jpg" and "number.jpg" but in both ways it randomly happene the thumbnail is uploaded... or not... according to the log files the jpg file always was found.

If you want me to upload my Thumbnails for testing reason just tell me and i will sent you.

**Comment by becast** [comment]
Bug found!

**Comment by Filgaja** [comment]
okay cool :D both? thumbnail upload and the 2 upload limit?

did it happened because of upload time on big videos?

cant wait fpr 0.9.4 :)

I am still realy happy and glad for your work

**Comment by becast** [comment]
It was because of upload times, sort of. The token could be expired by the time the upload finished, which did not affect the upload before but the uploading of Thumbnails and the next upload.

YouPloader now refreshes the token before Thumbnails & the next upload.

**Comment by Filgaja** [comment]
Bug Seems still to exist in new version 0.9.4:

https://gist.github.com/anonymous/d16df6e163b6ec1f13f46e9bb2766325

at the moment youploader is open and finished the uplaod of "Final Fantasy XV #023" but it do not upload the next video "Horizon Zero Dawn #023"

The Problem with thumbnails are solved, but i reached this "upload stop" error around 3-4 times since update (so i am sorry) issue still persist :(

**Comment by becast** [comment]
This is an entirely different issue, looks like an UTF-8 encoding issue of the "ä" umlaut.
"Could not create upload! Return: HTTP/1.1 400 Bad Request" instead of "Unauthorized"

**Comment by Filgaja** [comment]
Ah okay :D did not noticed that :) So if i would not use an "ä,ü,ö" within my titel this problem would not happen? :D but to bad the german language is full of thoose letters.

is there a way to fix the text-formatation?
thank you for your fast checkup! You are the best :) wish i could help you more then just reporting ^^

**Comment by becast** [comment]
Yeah, not sure why it happens I thought I did proper encoding on it but I'll have to double check when I'm home!
Closing this one and have refiled it as #48 to keep the issues clean :)
